DROP DATABASE IF EXISTS FinalProject_WLe41465_GBo51454;
CREATE DATABASE IF NOT EXISTS FinalProject_WLe41465_GBo51454;
USE FinalProject_WLe41465_GBo51454;

-- Create table logins
CREATE TABLE User (
    UserID INT(255) AUTO_INCREMENT NOT NULL PRIMARY KEY,
    StudentID VARCHAR(9) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    Name VARCHAR (255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Status TINYINT NOT NULL DEFAULT 0,
    VKey VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE Project (
    ProjectID INT(255) AUTO_INCREMENT NOT NULL PRIMARY KEY,
    Projectname VARCHAR(13) NOT NULL,
    Coursename VARCHAR(8) NOT NULL,
    Notice VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE Role (
    RoleID TINYINT NOT NULL PRIMARY KEY,
    UserType VARCHAR(50) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE User_Project_Role (
    UserID INT(255) NOT NULL,
    ProjectID INT(255) NOT NULL,
    RoleID TINYINT NOT NULL,
    PRIMARY KEY (UserID, ProjectID),
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ProjectID) REFERENCES Project(ProjectID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (RoleID) REFERENCES Role(RoleID)
) ENGINE=InnoDB;

CREATE TABLE Content (
    ContentID INT(255) AUTO_INCREMENT NOT NULL PRIMARY KEY,
    Filename VARCHAR(50) NOT NULL,
    Filesize VARCHAR(50) NOT NULL,
    FileExt VARCHAR(50) NOT NULL,
    FilePath VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE User_Project_Content (
    UserID INT(255) NOT NULL,
    ProjectID INT(255) NOT NULL,
    RoleID TINYINT NOT NULL,
    ContentID INT(255) NOT NULL,
    ModifyTime VARCHAR(20) NOT NULL,
    PRIMARY KEY (ContentID),
    FOREIGN KEY (ContentID) REFERENCES Content(ContentID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ProjectID) REFERENCES Project(ProjectID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (RoleID) REFERENCES Role(RoleID)
) ENGINE=InnoDB;

CREATE TABLE Task (
    TaskID INT(255) AUTO_INCREMENT NOT NULL PRIMARY KEY,
    Taskname VARCHAR(150) NOT NULL,
    Taskdetails VARCHAR(255),
    UserName VARCHAR(255)
) ENGINE = InnoDB;

CREATE TABLE User_Project_Task (
    UserID INT(255) NOT NULL,
    ProjectID INT(255) NOT NULL,
    RoleID TINYINT NOT NULL,
    TaskID INT(255) AUTO_INCREMENT NOT NULL PRIMARY KEY,
    Completion TINYINT NOT NULL DEFAULT 0,
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ProjectID) REFERENCES Project(ProjectID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (RoleID) REFERENCES Role(RoleID),
    FOREIGN KEY (TaskID) REFERENCES Task(TaskID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

INSERT INTO Role (RoleID, UserType) VALUES (1, 'Admin');
INSERT INTO Role (RoleID, UserType) VALUES (2, 'User');
INSERT INTO Role (RoleID, UserType) VALUES (3, 'Guest');
INSERT INTO Role (RoleID, UserType) VALUES (4, 'Suspended');